version: '3.8'

services:
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-localstack}'
    image: localstack/localstack
    ports:
      # - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - '127.0.0.1:4566:4566' # LocalStack Gateway
    environment:
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMODB_IN_MEMORY=1
      - DYNAMODB_HEAP_SIZE=2G
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - '8000:8000'
    command: ['-Xmx4G', '-jar', 'DynamoDBLocal.jar', '-inMemory', '-sharedDb']

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: 'http://dynamodb:8000'
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on:
      - dynamodb
